export const DEFAULT_MCP_SERVER_URL = 'https://mcp.reelsfarm.com/mcp';
export const DEFAULT_PROFILE = 'default';
export const SDK_NAME = 'reelsfarm-mcp-client';
export const SDK_VERSION = '3.0.0';
export const MCP_CONTRACT_VERSION = '2026-08-22.1';
export const DEFAULT_TIMEOUT_MS = 120_000;
export const DEFAULT_JOB_TIMEOUT_MS = 300_000;
export const CONFIRMATION_TTL_MS = 10 * 60 * 1000;
export const DEFAULT_OPERATION_RECOVERY_TIMEOUT_MS = 30_000;
